Repository mif-sge/verkehr, pull requests merged in 2019-05, with the labels that each got.

#13 merge current dev state into master
  CONTRIBUTING.md
  Documentation/Concepts/Technologies.drawio
  Documentation/Concepts/Technologies.png
  Documentation/Concepts/Visualization_Model.drawio
  Documentation/Concepts/Visualization_Model.png
  Documentation/Mockups/Verkehrs-Node.bmpr
  Documentation/Mockups/Verkehrs-Node.pdf
  Documentation/Protocols/Protocol_2019-04-26.md
  Documentation/Use Cases/Use-Case-Diagram.drawio
  Documentation/Use Cases/Use-Case-Diagram.pdf
  Documentation/Use Cases/Use-Case-Diagram_UC-VN-2.png
  Documentation/Use Cases/Use-Case-Diagram_UC-VN-3.png
  Documentation/Use Cases/Use-Case-Diagram_general.png
  Documentation/User Stories/UserStories.md
  README.md
  frontend/.gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/src/assest/css/App.css
  frontend/src/assest/css/index.css
  frontend/src/assest/img/logo.svg
  frontend/src/index.js
  frontend/src/routes/routes.js
  frontend/src/service/serviceWorker.js
  frontend/src/tests/App.test.js
  frontend/src/views/App.js
  frontend/src/views/Home.js
  frontend/src/views/Plan.js
  frontend/src/views/StreetMaps.js
Labels: enhancement, verkehr

#18 Merge current dev state into master
  Documentation/Activity Diagrams/Activity-Diagram.drawio
  Documentation/Activity Diagrams/Activity-Diagram_UC-VN-2.png
  Documentation/Activity Diagrams/Activity-Diagram_UC-VN-3.2.png
  Documentation/Activity Diagrams/Activity-Diagram_UC-VN-3.3.png
  Documentation/Activity Diagrams/Activity-Diagram_UC-VN-3.png
  Documentation/Activity Diagrams/Activity-Diagram_UC-VN-4.png
  Documentation/Activity Diagrams/Activity-Diagram_UC-VN-5.png
  Documentation/Activity Diagrams/Activity-Diagram_general.png
  Documentation/Concepts/Data_Model.drawio
  Documentation/Concepts/Data_Model.png
  Documentation/Concepts/Technologies.drawio
  Documentation/Concepts/Technologies.png
  Documentation/Mockups/- Buslinie auswählen - Linie 1.png
  Documentation/Mockups/- Buslinie auswählen -.png
  Documentation/Mockups/Einkaufszentrum.png
  Documentation/Mockups/Fahrplan.png
  Documentation/Mockups/Haltestelle.png
  Documentation/Mockups/Home.png
  Documentation/Mockups/Karte.png
  Documentation/Mockups/Krankenhaus.png
  Documentation/Mockups/Linie 1.png
  Documentation/Specifications/Specifications.md
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/routes/routes.js
  frontend/src/tests/Home.test.js
  frontend/src/tests/Plan.test.js
  frontend/src/tests/StreetMap.test.js
  frontend/src/views/StreetMap.js
Labels: enhancement, verkehr

#19 Add dockerfiles to build and start frontend #5
  frontend/Dockerfile
  frontend/build-docker.sh
  frontend/start-docker.sh
  frontend/stop-docker.sh
Labels: enhancement, verkehr

#24 Merge current dev state into master
  .travis.yml
  README.md
  backend/README.md
  backend/trafficnode-server/.gitignore
  backend/trafficnode-server/Dockerfile
  backend/trafficnode-server/app/lib/data.js
  backend/trafficnode-server/app/lib/database/connection.js
  backend/trafficnode-server/app/lib/database/models/Location.js
  backend/trafficnode-server/app/lib/database/models/Street.js
  backend/trafficnode-server/app/lib/world.js
  backend/trafficnode-server/app/routes/main/handlers/demo.js
  backend/trafficnode-server/app/routes/main/handlers/root.js
  backend/trafficnode-server/app/routes/main/index.js
  backend/trafficnode-server/bin/plugin-collector.js
  backend/trafficnode-server/bin/setup.js
  backend/trafficnode-server/build-docker.sh
  backend/trafficnode-server/config/manifest.js
  backend/trafficnode-server/index.js
  backend/trafficnode-server/logger.js
  backend/trafficnode-server/package-lock.json
  backend/trafficnode-server/package.json
  backend/trafficnode-server/prompt.js
  backend/trafficnode-server/server.js
  backend/trafficnode-server/start-docker.sh
  backend/trafficnode-server/stop-docker.sh
  backend/trafficnode-server/test/example-test.js
  frontend/Dockerfile
  frontend/build-docker.sh
  frontend/start-docker.sh
  frontend/stop-docker.sh
Labels: enhancement, verkehr

#26 Merge current dev state into Master
  Documentation/Activity Diagrams/Activity-Diagram.drawio
  Documentation/Activity Diagrams/Activity-Diagram_UC-VN-2.png
  Documentation/Activity Diagrams/Activity-Diagram_UC-VN-3.2.png
  Documentation/Activity Diagrams/Activity-Diagram_UC-VN-3.3.png
  Documentation/Activity Diagrams/Activity-Diagram_UC-VN-3.png
  Documentation/Activity Diagrams/Activity-Diagram_UC-VN-4.png
  Documentation/Activity Diagrams/Activity-Diagram_UC-VN-5.png
  Documentation/Activity Diagrams/Activity-Diagram_general.png
  Documentation/Use Cases/Use-Case-Diagram.drawio
  Documentation/Use Cases/Use-Case-Diagram.pdf
  Documentation/Use Cases/Use-Case-Diagram_UC-VN-2.png
  Documentation/Use Cases/Use-Case-Diagram_UC-VN-3.png
  Documentation/Use Cases/Use-Case-Diagram_general.png
Labels: documentation, verkehr

#29 Merge current dev state into master
  frontend/src/assest/css/App.css
  frontend/src/assest/img/logo.png
  frontend/src/assest/styles/AppStyle.js
  frontend/src/assest/styles/HomeStyle.js
  frontend/src/assest/styles/StreetMapStyle.js
  frontend/src/components/ListItemLink.js
  frontend/src/routes/routes.js
  frontend/src/views/App.js
  frontend/src/views/Home.js
  frontend/src/views/StreetMap.js
Labels: enhancement, verkehr

#30 Merge current dev state into master
  backend/trafficnode-server/Dockerfile
  backend/trafficnode-server/app/lib/database/connection.js
  backend/trafficnode-server/app/routes/main/index.js
  backend/trafficnode-server/config/manifest.js
  backend/trafficnode-server/server.js
  docker-compose.yml
  frontend/Dockerfile
  frontend/package-lock.json
  frontend/package.json
  frontend/src/urls/urls.js
  frontend/src/views/Home.js
  frontend/src/views/Plan.js
  frontend/start-docker.sh
Labels: enhancement, verkehr

#34 Merge current dev state into master
  backend/README.md
  backend/trafficnode-server/app/lib/database/connection.js
  docker-compose.yml
  verkehr.env
Labels: bug, verkehr

#36 Merge current dev state into master
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/assest/styles/PlanStyle.js
  frontend/src/tubedata/tubedata.json
  frontend/src/views/Home.js
  frontend/src/views/Plan.js
Labels: enhancement, verkehr

#37 Merge current dev state into master
  frontend/src/views/App.js
  frontend/src/views/Home.js
Labels: enhancement, verkehr

#43 Merge current dev state into master
  Documentation/Specifications/ClientServerCommunication.md
  backend/README.md
  backend/trafficnode-server/app/events/location-created.js
  backend/trafficnode-server/bin/event-system.js
  backend/trafficnode-server/index.js
  backend/trafficnode-server/package-lock.json
  backend/trafficnode-server/package.json
  frontend/src/assest/styles/InfoLabelStyle.js
  frontend/src/assest/styles/SnackBarContentWrapperStyle.js
  frontend/src/backendCommunication/fetchRequests.js
  frontend/src/backendCommunication/urls.js
  frontend/src/components/InfoLabel.js
  frontend/src/components/SnackbarContentWrapper.js
  frontend/src/views/App.js
  frontend/src/views/Home.js
Labels: enhancement, verkehr
